In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.utils import plot_model

In [2]:
csv_file=tf.keras.utils.get_file('heart.csv', 'https://storage.googleapis.com/download.tensorflow.org/data/heart.csv')

24576/13273 [=======================================================] - 0s 0us/step


In [3]:
df=pd.read_csv(csv_file)

In [4]:
df.head()

age  sex  cp  trestbps  chol  ...  oldpeak  slope  ca        thal  target
0   63    1   1       145   233  ...      2.3      3   0       fixed       0
1   67    1   4       160   286  ...      1.5      2   3      normal       1
2   67    1   4       120   229  ...      2.6      2   2  reversible       0
3   37    1   3       130   250  ...      3.5      3   0      normal       0
4   41    0   2       130   204  ...      1.4      1   0      normal       0

[5 rows x 14 columns]

In [5]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal         object
target        int64
dtype: object

In [6]:
df['thal']=pd.Categorical(df['thal'])
df['thal']=df.thal.cat.codes

In [7]:
df.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   1       145   233    1  ...      0      2.3      3   0     2       0
1   67    1   4       160   286    0  ...      1      1.5      2   3     3       1
2   67    1   4       120   229    0  ...      1      2.6      2   2     4       0
3   37    1   3       130   250    0  ...      0      3.5      3   0     3       0
4   41    0   2       130   204    0  ...      0      1.4      1   0     3       0

[5 rows x 14 columns]

In [8]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal           int8
target        int64
dtype: object

In [9]:
target=df.pop('target')

In [10]:
dataset=tf.data.Dataset.from_tensor_slices((df.values,target.values))

In [11]:
for feat,targ in dataset.take(6):
  print('features:{},target:{}'.format(feat,targ))

features:[ 63.    1.    1.  145.  233.    1.    2.  150.    0.    2.3   3.    0.
   2. ],target:0
features:[ 67.    1.    4.  160.  286.    0.    2.  108.    1.    1.5   2.    3.
   3. ],target:1
features:[ 67.    1.    4.  120.  229.    0.    2.  129.    1.    2.6   2.    2.
   4. ],target:0
features:[ 37.    1.    3.  130.  250.    0.    0.  187.    0.    3.5   3.    0.
   3. ],target:0
features:[ 41.    0.    2.  130.  204.    0.    2.  172.    0.    1.4   1.    0.
   3. ],target:0
features:[ 56.    1.    2.  120.  236.    0.    0.  178.    0.    0.8   1.    0.
   3. ],target:0


In [12]:
tf.constant(df['thal'])

<tf.Tensor: shape=(303,), dtype=int8, numpy=
array([2, 3, 4, 3, 3, 3, 3, 3, 4, 4, 2, 3, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3,
       3, 4, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 4, 2, 4, 3, 4, 3, 4, 4,
       2, 3, 3, 4, 3, 3, 4, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 4,
       4, 2, 3, 3, 4, 3, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 3, 3, 4, 4, 4,
       3, 3, 4, 3, 4, 4, 3, 4, 3, 3, 3, 4, 3, 4, 4, 3, 3, 4, 4, 4, 4, 4,
       3, 3, 3, 3, 4, 3, 4, 3, 4, 4, 3, 3, 2, 4, 4, 2, 3, 3, 4, 4, 3, 4,
       3, 3, 4, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
       4, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 3, 2,
       4, 4, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 2, 2, 4, 3, 4, 2, 4, 3,
       3, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 2, 2, 4, 3, 4, 3, 2, 4, 3, 3, 2,
       4, 4, 4, 4, 3, 0, 3, 3, 3, 3, 1, 4, 3, 3, 3, 4, 3, 4, 3, 3, 3, 4,
       3, 3, 4, 4, 4, 4, 3, 3, 4, 3, 4, 3, 4, 4, 3, 4, 4, 3, 4, 4, 3, 3,
      

In [13]:
train_dataset=dataset.shuffle(len(df)).batch(1)

In [14]:
def get_compiled_model():
  model=tf.keras.Sequential([
                             tf.keras.layers.Dense(10,activation='relu'),
                             tf.keras.layers.Dense(10,activation='relu'),
                             tf.keras.layers.Dense(1)
  ])
  model.compile(loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                optimizer=tf.keras.optimizers.Adam(),
                metrics=['accuracy'])
  return model

In [15]:
model=get_compiled_model()
model.fit(train_dataset,epochs=15)

Epoch 1/15
303/303 [==============================] - 1s 1ms/step - loss: 7.3898 - accuracy: 0.6766
Epoch 2/15
303/303 [==============================] - 0s 1ms/step - loss: 1.0915 - accuracy: 0.6502
Epoch 3/15
303/303 [==============================] - 0s 1ms/step - loss: 0.9179 - accuracy: 0.6997
Epoch 4/15
303/303 [==============================] - 0s 1ms/step - loss: 0.9180 - accuracy: 0.6832
Epoch 5/15
303/303 [==============================] - 0s 1ms/step - loss: 0.8243 - accuracy: 0.7030
Epoch 6/15
303/303 [==============================] - 0s 1ms/step - loss: 0.7190 - accuracy: 0.7195
Epoch 7/15
303/303 [==============================] - 0s 1ms/step - loss: 0.6391 - accuracy: 0.7261
Epoch 8/15
303/303 [==============================] - 0s 1ms/step - loss: 0.6735 - accuracy: 0.7459
Epoch 9/15
303/303 [==============================] - 0s 1ms/step - loss: 0.6411 - accuracy: 0.7162
Epoch 10/15
303/303 [==============================] - 0s 1ms/step - loss: 0.5975 - accuracy: 0.7228

In [16]:
inputs={key:tf.keras.layers.Input(shape=(),name=key) for key in df.keys()}
inputs = {key: tf.keras.layers.Input(shape=(), name=key) for key in df.keys()}
x = tf.stack(list(inputs.values()), axis=-1)

x = tf.keras.layers.Dense(10, activation='relu')(x)
output = tf.keras.layers.Dense(1)(x)

model_func = tf.keras.Model(inputs=inputs, outputs=output)

model_func.compile(optimizer='adam',
                   loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                   metrics=['accuracy'])

In [17]:
dict_slices = tf.data.Dataset.from_tensor_slices((df.to_dict('list'), target.values)).batch(16)

In [18]:
for dict_slice in dict_slices.take(1):
  print (dict_slice)

({'age': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([63, 67, 67, 37, 41, 56, 62, 57, 63, 53, 57, 56, 56, 44, 52, 57],
      dtype=int32)>, 'sex': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1], dtype=int32)>, 'cp': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 4, 4, 3, 2, 2, 4, 4, 4, 4, 4, 2, 3, 2, 3, 3], dtype=int32)>, 'trestbps': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([145, 160, 120, 130, 130, 120, 140, 120, 130, 140, 140, 140, 130,
       120, 172, 150], dtype=int32)>, 'chol': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([233, 286, 229, 250, 204, 236, 268, 354, 254, 203, 192, 294, 256,
       263, 199, 168], dtype=int32)>, 'fbs': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0], dtype=int32)>, 'restecg': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0, 0], dtype=int32)>, 'thalach': <tf.Tensor: shape=(16

In [19]:
model_func.fit(dict_slices, epochs=15)

Epoch 1/15
19/19 [==============================] - 1s 2ms/step - loss: 36.8276 - accuracy: 0.2871
Epoch 2/15
19/19 [==============================] - 0s 2ms/step - loss: 10.6248 - accuracy: 0.4323
Epoch 3/15
19/19 [==============================] - 0s 2ms/step - loss: 3.6765 - accuracy: 0.7096
Epoch 4/15
19/19 [==============================] - 0s 2ms/step - loss: 3.0243 - accuracy: 0.7294
Epoch 5/15
19/19 [==============================] - 0s 2ms/step - loss: 2.7448 - accuracy: 0.7030
Epoch 6/15
19/19 [==============================] - 0s 2ms/step - loss: 2.5588 - accuracy: 0.7030
Epoch 7/15
19/19 [==============================] - 0s 2ms/step - loss: 2.4128 - accuracy: 0.7129
Epoch 8/15
19/19 [==============================] - 0s 2ms/step - loss: 2.2974 - accuracy: 0.7129
Epoch 9/15
19/19 [==============================] - 0s 2ms/step - loss: 2.2005 - accuracy: 0.7129
Epoch 10/15
19/19 [==============================] - 0s 2ms/step - loss: 2.1160 - accuracy: 0.7129
Epoch 11/15
19/19

0    2
1    3
2    4
3    3
4    3
5    3
6    3
7    3
8    4
9    4
Name: thal, dtype: int8